# Generated by Django 4.2.2 on 2023-07-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=115)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(upload_to='photos/%y/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('main_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.maincategories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=115, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%y/')),
                ('price', models.CharField(default='0', max_length=20, verbose_name='Стоимость')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.lastcategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ['title', 'availability', 'price', 'cat'],
            },
        ),
        migrations.AddField(
            model_name='lastcategories',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.subcategories'),
        ),
    ]
