# Generated by Django 4.2.2 on 2023-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategories',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Категория 1го уровня', 'verbose_name_plural': 'Категории 1го уровня'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Категория 2го уровня', 'verbose_name_plural': 'Категории 2го уровня'},
        ),
    ]
