# Generated by Django 4.2.1 on 2023-05-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=115)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%y/')),
            ],
        ),
    ]
