# Generated by Django 4.2.2 on 2023-06-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_lastcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastcategories',
            old_name='main_cat',
            new_name='sub_cat',
        ),
    ]
