# Generated by Django 4.2.2 on 2023-07-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_maincategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastcategories',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Категория 3го уровня', 'verbose_name_plural': 'Категории 3го уровня'},
        ),
    ]
