# Generated by Django 4.2.1 on 2023-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_shoptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptable',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoptable',
            name='price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
