# Generated by Django 4.2.1 on 2023-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_lastcategories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%y/')),
                ('text_on_photo_head', models.CharField(blank=True, max_length=255)),
                ('text_on_photo_lower', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='0 руб.', max_length=20, verbose_name='Стоимость'),
        ),
    ]
