# Generated by Django 4.2.2 on 2023-06-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_category_shoptable_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('main_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainsite.maincategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameModel(
            old_name='ShopTable',
            new_name='Products',
        ),
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainsite.subcategories'),
        ),
    ]
