# Generated by Django 4.2.2 on 2023-06-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_product_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastcategories',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'availability', 'price', 'cat'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='lastcategories',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainsite.lastcategories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=20, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=115, verbose_name='Название'),
        ),
    ]
