# Generated by Django 4.2.2 on 2023-06-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_maincategory_subcategories_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=115)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%y/')),
                ('price', models.CharField(default='0', max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainsite.subcategories')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
