# Generated by Django 4.2.1 on 2023-10-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_usercart'),
        ('orders', '0005_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='mainsite.product'),
        ),
    ]
