# Generated by Django 4.2.1 on 2023-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_user_id_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_sum',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
